# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('with_us', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30)),
                ('main_colour', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
            ],
        ),
    ]
