# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('with_us', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30)),
                ('main_colour', models.CharField(choices=[('#000000', 'black'), ('#808080', 'gray'), ('#C0C0C0', 'silver'), ('#FFFFFF', 'white'), ('#800000', 'maroon'), ('#FF0000', 'red'), ('#808000', 'olive'), ('#FFFF00', 'yellow'), ('#008000', 'green'), ('#00FF00', 'lime'), ('#008080', 'teal'), ('#00FFFF', 'aqua'), ('#000080', 'navy'), ('#0000FF', 'blue'), ('#800080', 'purple'), ('#FF00FF', 'funchsia')], default='#FFFFFF', max_length=7)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
            ],
        ),
    ]
