# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('with_us', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollageMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CollageStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CollageSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(choices=[('#000000', 'black'), ('#808080', 'gray'), ('#C0C0C0', 'silver'), ('#FFFFFF', 'white'), ('#800000', 'maroon'), ('#FF0000', 'red'), ('#808000', 'olive'), ('#FFFF00', 'yellow'), ('#008000', 'green'), ('#00FF00', 'lime'), ('#008080', 'teal'), ('#00FFFF', 'aqua'), ('#000080', 'navy'), ('#0000FF', 'blue'), ('#800080', 'purple'), ('#FF00FF', 'funchsia')], default='#FFFFFF', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
                ('main_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DrawStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DrawSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
                ('main_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaintMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaintStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaintSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
                ('main_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PrintStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sculpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('original_img', sorl.thumbnail.fields.ImageField(upload_to=gallery.models.dir_name)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SculptMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SculptStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SculptSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sculpt',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.SculptMedium'),
        ),
        migrations.AddField(
            model_name='sculpt',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.SculptStyle'),
        ),
        migrations.AddField(
            model_name='sculpt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.SculptSubject'),
        ),
        migrations.AddField(
            model_name='print',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PrintMedium'),
        ),
        migrations.AddField(
            model_name='print',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PrintStyle'),
        ),
        migrations.AddField(
            model_name='print',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PrintSubject'),
        ),
        migrations.AddField(
            model_name='photo',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoMedium'),
        ),
        migrations.AddField(
            model_name='photo',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoStyle'),
        ),
        migrations.AddField(
            model_name='photo',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoSubject'),
        ),
        migrations.AddField(
            model_name='paint',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PaintMedium'),
        ),
        migrations.AddField(
            model_name='paint',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PaintStyle'),
        ),
        migrations.AddField(
            model_name='paint',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PaintSubject'),
        ),
        migrations.AddField(
            model_name='draw',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.DrawMedium'),
        ),
        migrations.AddField(
            model_name='draw',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.DrawStyle'),
        ),
        migrations.AddField(
            model_name='draw',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.DrawSubject'),
        ),
        migrations.AddField(
            model_name='collage',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.CollageMedium'),
        ),
        migrations.AddField(
            model_name='collage',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.CollageStyle'),
        ),
        migrations.AddField(
            model_name='collage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.CollageSubject'),
        ),
    ]
