# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='ex_style',
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='ex_type',
            field=models.CharField(choices=[('Paint', (('Fine Art', 'Fine Art'), ('Abstract', 'Abstract'), ('Modern', 'Modern'), ('Street Art', 'Street Art'), ('Pop Art', 'Pop Art'))), ('Photo', (('Fine Art', 'Fine Art'), ('Portraiture', 'Portraiture'), ('Abstract', 'Abstract'), ('Documentary', 'Documentary'), ('Conceptual', 'Conceptual'))), ('Draw', (('Graffiti', 'Graffiti'), ('Abstract', 'Abstract'), ('Fine Art', 'Fine Art'), ('Pop Art', 'Pop Art'), ('Surrealism', 'Surrealism'))), ('Sculpt', (('Pop Art', 'Pop Art'), ('Abstract', 'Abstract'), ('Wall', 'Wall'), ('Figurative', 'Figurative'), ('Modern', 'Modern'))), ('Collage', (('Dada', 'Dada'), ('Pop Art', 'Pop Art'), ('Abstract', 'Abstract'), ('Surrealism', 'Surrealism'), ('Street Art', 'Street Art'))), ('Print', (('Fine Art', 'Fine Art'), ('Abstract', 'Abstract'), ('Art Deco', 'Art Deco'), ('Pop Art', 'Pop Art'), ('Folk Art', 'Folk Art')))], max_length=15),
        ),
    ]
